# ===== Perfil DEV: ejecucion en local contra MySQL local =====
# Crea antes la base de datos:  CREATE DATABASE chefstack_db;
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/chefstack_db?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# Muestra el SQL generado para facilitar el aprendizaje y la depuracion
spring.jpa.show-sql=true
